source/app/metrics.mjs
source/templates/classic/image.svg

Just fixes a few grammar and punctuation errors in the outputted svgs. See diff.
None

Fix a few grammatical errors

---

.gitignore
README.md
action.yml
package-lock.json
package.json
settings.example.json
source/app/action/index.mjs
source/app/setup.mjs
tests/metrics.test.js

Add new option `setup_community_templates` to allow use of templates from forks.

Feat community templates

---

README.md
action.yml
source/app/action/index.mjs
source/plugins/languages/index.mjs
tests/metrics.test.js

Add a new option to use custom languages colors

Add plugin_languages_colors option

---

README.md
source/plugins/languages/index.mjs
tests/metrics.test.js

I tried implementing complementary colors as a preset.
I didn't test it in your workflow but I tested the color set on my own page. So you might need to test before merge.
Maybe my example is not too good because one bar is filling almost everything but you get the idea of complementary colors.
Also I added it to your test file. Not sure if that is right. Might have to check that.
Complementary colors reference: [see here](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Color_star-en_%28tertiary_names%29.svg/1024px-Color_star-en_%28tertiary_names%29.svg.png)

Complementary lang colors

---

source/app/metrics.mjs
source/app/web/instance.mjs
source/plugins/activity/index.mjs
source/plugins/gists/index.mjs
source/plugins/habits/index.mjs
source/plugins/isocalendar/index.mjs
source/plugins/lines/index.mjs
source/plugins/people/index.mjs
source/plugins/projects/index.mjs
source/plugins/stargazers/index.mjs
source/plugins/stars/index.mjs
source/plugins/topics/index.mjs
source/queries/common.organization.graphql
source/queries/people.repository.graphql
source/queries/people.sponsors.graphql
source/queries/projects.graphql
source/queries/projects.repository.graphql
source/queries/repositories.graphql
source/queries/repository.graphql
source/templates/common.mjs
source/templates/repository/template.mjs

Add basic support for organizations
**Fixes**

Add basic support for organizations

---

source/app/action/index.mjs
source/app/metrics/setup.mjs
source/app/mocks/api/axios/get/pagespeed.mjs
source/app/mocks/api/axios/get/spotify.mjs
source/app/mocks/api/axios/get/twitter.mjs
source/app/mocks/api/axios/post/anilist.mjs
source/app/mocks/api/axios/post/spotify.mjs
source/app/web/instance.mjs
source/plugins/base/index.mjs
source/plugins/core/index.mjs
source/plugins/core/metadata.yml

Add support for :
```yaml
token: NOT_NEEDED
committer_token: ${{ secrets.GITHUB_TOKEN }}
```
So it's possible to use standalone plugins without the need of creating a personal token when no GitHub related data are displayed

Add support for token "NOT_NEEDED" for standalone plugins

---

source/app/metrics/utils.mjs
source/plugins/base/index.mjs
source/plugins/languages/README.md
source/plugins/languages/index.mjs
source/plugins/languages/metadata.yml
source/templates/classic/partials/languages.ejs
source/templates/classic/style.css
tests/testscases.js

Add `plugin_languages_details` option to lets user display additional details of their languages stats.
```yaml
- uses: lowlighter/metrics@latest
with:
plugin_languages: yes
plugin_languages_details: bytes-size, percentage             # Additionally display total bytes size and percentage
```
**Default**
**1 section (percentage)**
**2 sections (percentage + bytes-size)**

Add option plugin_languages_details

---

package-lock.json
package.json
source/app/metrics/utils.mjs
source/plugins/music/README.md
source/plugins/music/index.mjs
source/plugins/music/metadata.yml
source/templates/classic/partials/music.ejs

**This pr only effects spotify in recent mode**
This displays when the music was played!

add when it was played for spotify in recent mode

---

source/app/mocks/api/github/rest/activity/listEventsForAuthenticatedUser.mjs
source/app/mocks/api/github/rest/activity/listRepoEvents.mjs
source/app/web/statics/app.placeholder.js
source/plugins/activity/index.mjs
source/plugins/activity/metadata.yml
source/templates/classic/style.css
source/templates/repository/partials/_.json
source/templates/repository/partials/activity.ejs

This add new features to *activity* plugin:
- Add `plugin_activity_visibility` to limit visibility to public events when using a `repo` scope token
- Add  `plugin_activity_timestamps` to display events dates
- `repository` template now supports activity plugin
- Organization activity now display actor name 
- Title are now ellipsed (`...`) instead of being cropped

Add support for repository template, plugin_activity_visibility and plugin_activity_timestamps

---

CONTRIBUTING.md
package-lock.json
package.json
source/app/metrics/index.mjs
source/app/metrics/utils.mjs
source/plugins/core/README.md
source/plugins/core/metadata.yml
source/plugins/core/tests.yml
source/templates/classic/style.css

Implement twemojis support to support more consistent render across all platforms through `config_twemoji` option:
<table>
<tr>
<th>Native (windows)</th><th>(Twemojis)</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/22963968/107554109-c7d89c80-6bd5-11eb-91ea-84e7fc631359.png"></td>
<td><img src="https://user-images.githubusercontent.com/22963968/107554093-c0b18e80-6bd5-11eb-89aa-75c822632e88.png"></td>
</tr>
</table>

Add option to use twemojis instead of emojis

---

source/app/mocks/api/github/graphql/introduction.organization.mjs
source/app/mocks/api/github/graphql/introduction.repository.mjs
source/app/mocks/api/github/graphql/introduction.user.mjs
source/app/web/statics/app.placeholder.js
source/plugins/introduction/README.md
source/plugins/introduction/index.mjs
source/plugins/introduction/metadata.yml
source/plugins/introduction/queries/organization.graphql
source/plugins/introduction/queries/repository.graphql
source/plugins/introduction/queries/user.graphql
source/plugins/introduction/tests.yml
source/templates/classic/partials/_.json
source/templates/classic/partials/introduction.ejs
source/templates/classic/style.css
source/templates/repository/partials/_.json
source/templates/repository/partials/introduction.ejs

The *introduction* plugin display your account bio or your organization/repository description.
It is mostly intended for metrics used outside of GitHub, since these informations are already available on GitHub.

Add introduction plugin

---

source/app/mocks/api/github/rest/repos/listCommits.mjs
source/plugins/contributors/README.md
source/plugins/contributors/index.mjs
source/plugins/contributors/metadata.yml
source/plugins/contributors/tests.yml
source/plugins/habits/index.mjs
source/templates/classic/style.css
source/templates/repository/partials/contributors.ejs
source/templates/repository/template.mjs

- Add `plugin_contributors_ignored` option to ignore users (useful to remove bot users like GitHub Action)
- Add `plugin_contributors_contributions` option to display number of commits per contributors

Add new option to contributors plugin

---

.github/readme/partials/setup/web.md
source/app/web/instance.mjs
source/app/web/settings.example.json
source/app/web/statics/app.js
source/app/web/statics/app.placeholder.js
source/app/web/statics/index.html
source/app/web/statics/style.css
source/plugins/core/metadata.yml

- Remove static resources rate-limit headers
- Add base/core options in web
- Add alias for repository url
- Detailed error messages
- Prevent multiple requests for a single user
- Add footer with license

Improve web instance

---

source/plugins/people/README.md
source/plugins/people/index.mjs
source/plugins/people/metadata.yml
source/plugins/people/tests.yml

Add new option `plugin_people_sponsors_custom` to people plugin to let specify custom sponsors (intended for unsupported GitHub sponsors sources)

Add plugin_people_sponsors_custom option

---

action.yml
source/app/action/action.yml
source/plugins/core/metadata.yml

Workflows runs using `lowlighter/metrics@master` will now use the prebuilt docker images from [GitHub container registry](https://github.com/users/lowlighter/packages/container/metrics/versions) instead of rebuilding image which will reduce workflow duration by ~ 5 to 10 minutes.
`use_prebuilt_image` option has been transformed into a boolean (enabled by default)

Feat docker prevuilt

---

CONTRIBUTING.md
package-lock.json
package.json
source/app/metrics/index.mjs

Switch from [libxmljs/libxmljs](https://github.com/libxmljs/libxmljs) to [marudor/libxmljs2](https://github.com/marudor/libxmljs2) (which is fork of libxmljs supporting newer versions of node)
This does not introduce any api changes.
Closes #185

Use libxmljs2 instead of libxmljs

---

source/app/web/instance.mjs

Redirect multiple http requests for same login into the same request instead of returning a 409 error

Redirect multiple requests in same request instead in web server

---

package-lock.json
package.json
source/app/metrics/utils.mjs
source/plugins/skyline/README.md
source/plugins/skyline/index.mjs
source/plugins/skyline/metadata.yml
source/plugins/skyline/tests.yml
source/templates/classic/partials/skyline.ejs
source/templates/classic/style.css

Skyline plugin will now use base64 encoded gif by default which is way more optimized (both in rendering and in file size) than using hacks using CSS animations.
Animated gifs within GitHub context is not supported by some browsers (notably Firefox and Safari), but previous behaviour can be enabled again using `plugin_skyline_compatibility: yes`.

Switch skyline to GIF and add plugin_skyline_compatibility option

---

source/app/action/index.mjs

This will send a test request before rendering to verify that given token is valid and can be used.
Using a `HEAD` request, it'll check whether it throws a `401 Bad credentials` (i.e. invalid token) or a response without `x-oauth-scopes` header (meaning that `GITHUB_TOKEN` has probably be used instead)

Improve token error msg

---

source/app/web/statics/about/index.html
source/app/web/statics/about/script.js
source/app/web/statics/about/style.css
source/app/web/statics/app.js
source/app/web/statics/index.html
source/app/web/statics/style.css

- Loading indicators
- Faster loading with delayed requests
- Better CSS

Improve UX on web instances

---

package-lock.json
package.json
source/app/metrics/index.mjs
source/app/metrics/utils.mjs
source/app/web/instance.mjs
source/app/web/statics/about/index.html
source/app/web/statics/about/script.js
source/app/web/statics/index.html
source/plugins/activity/index.mjs
source/plugins/stackoverflow/index.mjs
source/plugins/stackoverflow/metadata.yml
source/templates/classic/partials/activity.ejs
source/templates/classic/partials/stackoverflow.ejs
source/templates/classic/style.css

See #236
* `core` now has a markdown interpretation function (html sanitization will also be applied)
*`"inline"` sanitization (for svgs) will remove most of html tags 
* `"extended"` sanitization (for metrics insights) will sanitize html but keep most of text tags
* `codelines` option can be specified to trim `<code>` tags
* metrics insights now display server-side rendered markdown  
* html comments should not be displayed anymore
* stackoverflow plugin
* render code snippets (including stackoverflow flavored ones)
* add option `plugin_stackoverflow_lines_snippet`
* activity plugin
* render code snippets
* basic code highlighting

Markdown interpretation

---

source/plugins/activity/index.mjs

Condense the list of commits produced by a PushEvent to only the final merge commit if it is present. Resolve #241.

Condense merge commits

---

source/app/metrics/utils.mjs
source/templates/classic/partials/stackoverflow.ejs
source/templates/classic/style.css

Follow-up of #237 
- Improved code hightlighting
- For `"inline"` markdown mode
- Parse `<blockquote>` as `<i>`
- Parse `<hX>` as `<b>`
- Inline codes without languages indications with multiples lines will be displayed as multiline

Improve markdown support and css tokens

---

source/plugins/lines/index.mjs
source/plugins/lines/metadata.yml

Add `plugin_lines_skipped` option to ignore selected repositories from line count (see #247)

Add `plugin_lines_skipped` option

---

source/app/web/statics/about/index.html
source/app/web/statics/about/script.js

Resolve #254 
Turns links such as `https://github.com/lowlighter/metrics/issues/254` into `lowlighter/metrics#254` or `#254` depending on the repository.
Applies to both issues/PRs and commits.

Simplify GitHub URLs in comments

---

source/app/action/index.mjs
source/app/metrics/index.mjs
source/templates/markdown/example.md

This adds support to `<%- await embed(q) %>` syntax in markdown template to include SVGs metrics inside of markdown templates without requiring to multiple jobs.
Images will be pushed to `markdown_cache` folder and links included

Add `embed` method in markdown plugin

---

.github/quickstart/template/metadata.yml
CONTRIBUTING.md
source/app/action/index.mjs
source/app/metrics/index.mjs
source/app/metrics/metadata.mjs
source/app/metrics/setup.mjs
source/app/web/instance.mjs
source/plugins/core/index.mjs
source/plugins/core/metadata.yml
source/templates/classic/README.md
source/templates/classic/metadata.yml
source/templates/markdown/README.md
source/templates/markdown/metadata.yml
source/templates/repository/README.md
source/templates/repository/metadata.yml
source/templates/terminal/README.md
source/templates/terminal/metadata.yml

Add metadata to templates.
It allows:
- Auto-check compatibility in core plugin against account type / output format
- Auto defaults output format based on template
- Using `template.mjs` other than classic template for community template

Add templates metadata

---

source/plugins/wakatime/index.mjs
source/plugins/wakatime/metadata.yml

This PR adds the option to use a selfhosted wakatime instance for the wakatime plugin. 
I tested it against this project called [Wakapi](https://github.com/muety/wakapi) which mimics the same endpoints as wakatime does, so its just a matter of using a different api url

Add selfhosted wakatime integration (wakapi)

---

package-lock.json
package.json

* ✨ **Metrics insights**
* #237 Improved markdown and code snippets rendering 
* #237 Empty comments are not displayed anymore
* #262 GitHub urls for comments, issues and pull requests are now rendered with GitHub format
* 🎩 **Notable contributions**
* #240 Add support for `plugin_notable_filter` to filter contributions (based on GitHub search query filter)
* #240 Add support for `plugin_notable_repositories` to also display repository name along with organization name
* <img src="https://user-images.githubusercontent.com/22963968/115153409-fd867f80-a075-11eb-9182-2893174fa709.png" width="400">
* 📰 **Recent activity**
* #237 Improved markdown and code snippets rendering 
* #242 Merge commits now display as a single commit
* #244 Pushed commits are now display from most recent to oldest …

Release v3.8

---

.github/preview.mjs
package-lock.json
package.json
source/app/web/instance.mjs
source/app/web/statics/app.js
source/app/web/statics/index.html

This adds a button to the "Action code" tab of the web instance that will copy the rendered YAML
to the clipboard when clicked.
The minified clipboard.js code has been added to the JS files that the app serves.
Since this is a single page web app that will create and destroy the button's DOM element, the
tab is watched, and the `ClipboardJS` instance is created when the user switches to the "Action code"
tab, and destroyed when the user switches to a different tab.
Resolves #253
***
I didn't apply much styling to the button, let me know if it should look different or be in a different position :smiley:

WEB: Add copy button to action tab

---

source/app/metrics/utils.mjs
source/plugins/core/README.md
source/plugins/core/metadata.yml

Edit the resizer to accept both absolute and relative values for `config_padding` option
This also edit default padding to attempt matching a correct size

Accept both absolute and relative values for config padding

---

source/app/metrics/utils.mjs
source/plugins/languages/README.md
source/plugins/languages/indepth.mjs
source/plugins/languages/index.mjs
source/plugins/languages/metadata.yml

Adds `plugin_languages_indepth` option for more accurate languages stats.
These are computed by cloning repositories, running github-linguist on it and processing each git log
(Still kind of experimental)

Add indepth languages analysis

---

source/app/web/statics/about/index.html
source/templates/classic/partials/activity.ejs
source/templates/classic/partials/posts.ejs
source/templates/classic/partials/rss.ejs
source/templates/markdown/partials/activity.ejs
source/templates/markdown/partials/posts.ejs
source/templates/repository/partials/activity.ejs
source/templates/repository/partials/rss.ejs

Adds timeZone argument to the date constructor in the recent activity plugin to add a timezone to the times. Should make it so that the times all display in the user's set timezone.
Haven't tested it though.
Fixes #324.

Use config timezone in all displayed times

---

source/app/web/statics/about/index.html
source/templates/classic/partials/habits.ejs

Copyedits coding habits section (most subject verb agreement) and change heading to "recent coding habits" as mentioning "recent activity" may confuse it with that plugin.

Copyedit coding habits plugin

---

source/plugins/stackoverflow/index.mjs

lowlighter in #344:
> Indeed, seems that anwser formatter has `comment_count:comments = 0` to handle this bug, but the question formatter has no default:
> https://github.com/lowlighter/metrics/blob/2ae690fac73120264a7221f821e0e708c11f3fc4/source/plugins/stackoverflow/index.mjs#L115
> 
> It would just need to append a `= 0` to default it when api doesn't return this field
This PR does so

Initialise StackOverflow comment count as 0

---

source/app/web/statics/about/style.css

The icons use `scale:transform(1.75)` which makes them exit their containers and clip into the text on mobile.
Adds a 2em margin to `.rankeds` to avoid this clipping.
#342.

Add margin to insights rankeds to avoid clipping

---

README.md
package-lock.json
package.json
source/app/metrics/metadata.mjs

* ↔️ **Introducing larger display size** <sup>✨ new!</sup>
* #310 You can now choose between `regular` (default) or `large` renders through `config_display` option
* #310 Plugins may render differently depending on size chosen
* *It is advised to keep `regular` size if you want metrics to be displayed well both on mobile and desktop (as on mobile it may be rescaled down when displayed)*
* <img src="https://user-images.githubusercontent.com/22963968/118713145-e3c98b00-b821-11eb-8744-db98cfdd291f.png" width="600">
* 🈷️ **Most used languages**
* #325 Add `plugin_languages_indepth` option to perform in-depth analysis of your languages statistics
* *This will clone your repositories, run [github/linguist](https://github.com/github/linguist) on them and iterate through matching `git log` …

Release v3.10

---

source/plugins/habits/index.mjs
source/plugins/languages/analyzers.mjs

This changes the way of how recents language activity is tracked
Basically it'll reproduce a partial state of repositories based on github events
Then it'll fetch `.gitattributes` to eventually handles overriden files for linguist
Also, since the recent languages activity part was moved from `habits` to `language` plugin, this simplify the code by linking them together (though plugins should be independant, this helps leveraging code maintaining since analyzer code is quite complex)
Relates #355

Reproduce partial repositories and fetch gitattributes for better recent languages

---

Dockerfile

Not sure which type of contribution this one should be as it doesn't seem to meet the criteria here: https://github.com/lowlighter/metrics/blob/1a5295115767cd5c7e15b6546399ff9fef377ba6/CONTRIBUTING.md#-accepted-contributions
This pull request will help speed up the Docker image build process, and also, make the built image smaller, by remove additional `apt-get update` and put the clean up process the end, which is the proper place for it.
Feel free to let me know if there is anything more I should do, thanks!

Improve apt process in Dockerfile

---

.github/readme/partials/setup/action/setup.md
README.md
source/app/web/statics/app.placeholder.js
source/plugins/core/README.md
source/plugins/core/index.mjs
source/plugins/core/metadata.yml
source/templates/classic/image.svg
source/templates/classic/style.css

Setting `config_display: columns` in the action and using  
`<img src="https://github.com/my-github-user/my-github-user/blob/master/github-metrics.svg" alt="Metrics" width="100%">`
in your README will create a two columns display on desktop:  
This PR is a followup of https://github.com/lowlighter/metrics/discussions/368

New "columns" display mode

---

source/app/web/statics/app.js

Was previously only matching and replacing the first underscore when
mapping a plugin option from `this.option.style` to `this_option_style`
(the actual result was `this_option.style`). This adjusts the regex to
match *each* `.` and replace it with `_`.
Fixes #378

Match all underscores for action options

---

source/plugins/languages/analyzers.mjs

Adds an optional chain because `file.repo_url` is nullable
- Resolve #415

Fix languages plugin crash

---

source/app/mocks/api/github/graphql/discussions.categories.mjs
source/app/mocks/api/github/graphql/discussions.statistics.mjs
source/app/web/statics/app.placeholder.js
source/plugins/discussions/README.md
source/plugins/discussions/index.mjs
source/plugins/discussions/metadata.yml
source/plugins/discussions/queries/categories.graphql
source/plugins/discussions/queries/statistics.graphql
source/plugins/discussions/tests.yml
source/templates/classic/partials/_.json
source/templates/classic/partials/discussions.ejs

Add new discussion plugin to display how many discussion user has started, and how many comments and answers provided.
Also track most posted categories

Add new Discussions plugin

---

source/app/mocks/api/github/graphql/repositories.repository.mjs
source/app/web/statics/app.placeholder.js
source/plugins/repositories/README.md
source/plugins/repositories/index.mjs
source/plugins/repositories/metadata.yml
source/plugins/repositories/queries/repository.graphql
source/plugins/repositories/tests.yml
source/templates/classic/partials/_.json
source/templates/classic/partials/repositories.ejs

Add new repositories plugin which lets feature a list of chosen repositories

Add new Repositories plugin

---

Dockerfile
package-lock.json
package.json
source/plugins/habits/index.mjs
source/plugins/languages/analyzers.mjs

Using the `github-linguist` gem directly is a bit of a hack, and any changes to console.log output breaks Metrics, like what happened with the release of v7.16.
[Nixinova/Linguist](https://github.com/Nixinova/Linguist) is a Node port of `github-linguist` which allows for proper JavaScript language data generation.
This change also allows for `prose` and `data` languages to be included in any generated metrics as a new option if so desired.
- [Generated with metrics@master](https://github.com/Nixinova/Metrics-Testing-August-1/blob/44dc92e2ebe0f88531fb9ee988da3d9cdbca4834/github-metrics.svg)
- [Generated with this change](https://github.com/Nixinova/Metrics-Testing-August-1/blob/344414271c8b8b1ce16975c0d10c2c0c1722324e/github-metrics.svg)
- Fully resolve #424
- See also: #341

Replace `github-linguist` gem with Node port `Nixinova/Linguist`

---

source/app/web/settings.example.json
source/plugins/core/index.mjs
source/plugins/habits/README.md
source/plugins/habits/index.mjs
source/plugins/languages/README.md
source/plugins/languages/index.mjs
source/plugins/licenses/README.md
source/plugins/licenses/index.mjs

Because some plugins have extra features that requires to perform modifications on the host (like downloading files, child process, remote code executions, etc), these are not suited for web instances.
This add a flags to let hosters toggle extra features

Web instances: Add flags to enable unsafe extra features

---

source/plugins/base/index.mjs

GraphQL API only load last year commits. Switching to REST API lets whole commits count

Base: load all commits rather than only last year

---

Dockerfile

Removes the remaining dependencies used only by `github-linguist` to finish up #436.
Tested with [Action](https://github.com/Nixinova/Nixinova/runs/3275374843?check_suite_focus=true), no errors.

Remove unused `github-linguist` dependencies

---

source/plugins/discussions/index.mjs

Discussions are currently displayed unsorted; this change sorts them by amount before being displayed.

Sort discussion categories for display

---

source/templates/classic/partials/followup.ejs

- Resolve #460
Changes the name listed in the followup headers to priorities display name with a fallback to username as [query]`.name` is nullable.
Also removes the ends-with-s check as "Names's" isn't incorrect.
*Sidenote,  `[...string].pop() === x` is quite an overcomplicated way of doing `string.endsWith(x)`.*

Use display name instead of username in followup plugin

---

source/app/mocks/api/github/graphql/achievements.default.mjs
source/plugins/achievements/list/users.mjs
source/plugins/achievements/queries/achievements.graphql

Add new achievements chatter (based on discussions started/comments) and helper (based on answered discussions):

Achievements plugin: add chatter and helper achievements

---

source/templates/repository/partials/base.header.ejs
source/templates/repository/template.mjs

Repository template now display stats about users (if it's a github action)
This is performed by looking if an `action.yml` exists on target repository, and then by using search code for `uses ${login} ${repo} path:.github/workflows language:YAML` and counting results

Repository: add number action users statistic

---

.github/workflows/workflow.yml
package.json

Script `npm run fmt` uses package [`dprint`](https://www.npmjs.com/package/dprint) which is not included in `package.json`'s `devDependencies`. 
https://github.com/lowlighter/metrics/blob/8f49d1076a1f2dfdfaab3edb62dedfddba0dfbb0/package.json#L15
https://github.com/lowlighter/metrics/blob/8f49d1076a1f2dfdfaab3edb62dedfddba0dfbb0/package.json#L63-L68
Module `dprint` is not used in a Node context so should not be placed in `package.json`.
It is just used in a CLI context:
https://github.com/lowlighter/metrics/blob/aabb21fbd71290c1874acefe8a9d125f81f80e75/.github/workflows/workflow.yml#L43-L48
This means that line 48 can just be changed to the content of the `fmt` script.
This would avoid an npm script being unrunnable outside of the CI process.
This PR inlines it in the `workflow.yml` file …

Move non-Node script from `package.json` to workflow

---

action.yml
source/plugins/languages/README.md
source/plugins/languages/analyzers.mjs
source/plugins/languages/index.mjs
source/plugins/languages/metadata.yml
source/plugins/languages/tests.yml

- Implement #341
Adds array options `plugin_languages_categories` and `plugin_languages_recent_categories` which configure which Linguist categories (`data, markup, programming, prose`) to display.
Test using `plugin_languages_categories: programming`:
Test using `programming` for most-used and `markup,data,prose` for recent:

Add options to configure which language categories to display

---

source/plugins/repositories/README.md

The current example of repositories plugin uses `plugin_repositories_lists`, but it should be `plugin_repositories_featured`.

Fix typo in repository plugin example

---

source/plugins/languages/analyzers.mjs

Skip merge commits (assuming parents > 2) from recent language analysis 
Closes #502

fix(plugins/languages): skip merge commits from recent analysis

---

source/plugins/languages/analyzers.mjs

If the language result was null the plugin was crashing. This fixes it.

Fix language plugin crash

---

source/plugins/isocalendar/index.mjs
source/plugins/isocalendar/metadata.yml

Isocalendar additional stats are now computed over all account contributions, rather on the loaded isometrics view to avoid capping at `isocalendar.duration` time window

feat(plugins/isocalendar): make stats based on overall account contributions rather than restricted to `isocalendar.duration`

---

source/plugins/isocalendar/index.mjs

Fix regression caused by #528, the max used as reference to scale bars was using the all-time max rather than the max in the time frame
Fix #530

fix(plugins/isocalendar): use local max rather than all-time max for bars scaling

---

source/plugins/base/index.mjs

*(Followup of #598)*
When fetching repositories, if the request timeout for a given repositories batch settings, it'll retry automatically by halving values (i.e. fetch 100 repositories, then 50, 25, 12, 6, 3, 1). In case of timeout for fetching a single repository, the plugin will fail.
This should avoid "unlucky" runs for "huge users" by providing a higher success rate

fix(plugins/base): automatic halving of repositories batching when fetching them

---

source/plugins/code/index.mjs
source/plugins/habits/index.mjs
source/plugins/languages/analyzers.mjs

`commits_authoring` defaults to `.user.login` (unless overidden) but it actually doesn't match in most of plugin using this option which ends up with no results though it should

fix(plugins/code,habits,languages): support basic login as authoring

---

source/plugins/notable/index.mjs
source/plugins/notable/metadata.yml
source/plugins/notable/queries/commits.graphql
source/templates/classic/partials/notable.ejs
source/templates/classic/style.css

Closes #615 
Current preview: 
Questions: 
- how to display "earned stars" ? or should we just display the total amount in a stats field, like an overall contribution score ?
- tried to keep same color scheme as achievement, but this kind of look chaotic there, maybe just keep 2 thresholds ? (maintainer + more than X% ?)
- should probably display <1% as "<1%" instead of "1%"
- need to find a good threshold, contributing to open source projects is hard so we should find a balance with "active contributor" and "occasional contributor"

feat(plugins/notable): add `indepth` mode

---

source/app/metrics/index.mjs
source/app/metrics/utils.mjs
source/plugins/core/metadata.yml

Closes #662
This improves `optimize` option to support:
- `css`: purge and minify css with [FullHuman/purgecss](https://github.com/FullHuman/purgecss) and [css/csso](https://github.com/css/csso)
- `xml`: pretty-print xml with [chrisbottin/xml-formatter](https://github.com/chrisbottin/xml-formatter)
- `svg`: optimization with [svg/svgo](https://github.com/svg/svgo) (experimental, see #172 for more info)
- experimental flag `--optimize` has been renamed `--optimize-svg`

feat(metrics): improved optimizers

---

source/plugins/poopmap/metadata.yml

This PR fixes the issue where `plugin_poopmap_days` is always `7`, regardless of input value

fix: update plugin_poopmap_days to number type

---

source/app/web/instance.mjs
source/app/web/statics/app.js

Closes #719
Required and advised scopes will be required.
If no token is required, the web app will suggest using `token: NOT_NEEDED`

feat(app/web): display required scopes in action code

---

source/app/action/index.mjs

Fix an issue with the base64-to-cache regex replacer for markdown template
Because of the `/g` flag, `regex.exec` was starting from `lastIndex` but in the meantime `rendered` variable was modified in-place, causing "jumps" in the loop

fix(app/action): base64-to-cache regex

---

source/app/action/index.mjs
source/plugins/core/README.md
source/plugins/core/metadata.yml

Closes #728
Add a retry wrapper around different output actions along with two new options `retries_output_action` and `retries_delay_output_action` to automatically retry upon API errors (rate-limit, connection reset, etc.)

feat(action): add `retries_output_action` and `retries_delay_output_action`

---

source/app/metrics/utils.mjs

Closes #691
The issue was only fixed for code blocks without languages highlighting

fix(app/utils): indent for code block with languages hightlighting

---

source/plugins/isocalendar/index.mjs

Closes #753
Relates to #598
- This removes the "padding" trick to just force the starting date on a sunday (day 0 in JS)
- It also forces the time to be set at 00:00:00.000 for starting ranges and 23:59:59.999 for ending ranges, rather than keeping the current time, which could causes some days to be misreported
- Calendar are now fetched 4 weeks (28 days) at a time to avoid API timeouts for large users
- Merged the fetching between isocalendar and other statistics to avoid duplicate calls
___

fix(plugins/isocalendar): algorithm improvements for date ranges

---

source/app/web/statics/app.placeholder.js
source/plugins/starlists/README.md
source/plugins/starlists/index.mjs
source/plugins/starlists/metadata.yml
source/plugins/starlists/tests.yml
source/templates/classic/partials/_.json
source/templates/classic/partials/starlists.ejs
source/templates/classic/style.css

Add support for GitHub stars lists
As this GitHub feature is currently in beta and no API is available yet (see https://github.com/github/feedback/discussions/8293), additional complex features for this plugin may be postponed until the release (as puppeteer is the least stable plugin type)
Semi-related: #712

feat(plugins/starlists): add new starlists plugin

---

source/plugins/topics/README.md
source/plugins/topics/index.mjs
source/plugins/topics/metadata.yml
source/templates/classic/partials/topics.ejs

This add `labels` alias for `plugin_topics_mode` to match with `icons`.
Old values `mastered` and `starred` still retain their previous behaviour
Also migrate to new documentation format

feat(plugins/topics): add `labels` alias

---

source/templates/classic/partials/activity.ejs
source/templates/classic/style.css
source/templates/repository/partials/activity.ejs

Long commit messages should now be cropped gracefully with an ellipsis `...`

fix(plugins/activity): ellipsis for long commit messages

---

source/app/metrics/index.mjs
source/app/metrics/utils.mjs
source/app/web/settings.example.json
source/plugins/core/metadata.yml

Add support for `extras_js` to inject raw js during image rendering in puppeteer context

feat(app/metrics): add `extras_js` support

---

source/app/metrics/metadata.mjs
source/app/metrics/presets.mjs
source/app/web/instance.mjs
source/app/web/settings.example.json
source/plugins/core/README.md
source/plugins/core/examples.yml
source/plugins/core/metadata.yml

Relates to #799
This introduces presets for web instances
Support for action will come in the next days

feat(app/web): add support for `config.presets`

---

source/plugins/base/index.mjs
source/plugins/base/queries/organization.x.graphql
source/plugins/base/queries/user.x.graphql

Since #598, the base plugin always perform a lot a query even for a single user.
This attempt to use the older method first and fallback to unit query if needed

feat(plugins/base): add bulk query and fallback to unit query

---

package-lock.json
package.json
source/app/metrics/index.mjs
source/app/metrics/utils.mjs
source/plugins/core/metadata.yml

feat(plugins/core): add `config_octicon` support

---

.github/readme/partials/documentation/setup/docker.md
source/app/action/index.mjs
source/app/metrics/metadata.mjs

fix(app/docker): correctly parse input variables

---

source/app/metrics/index.mjs

fix(app/metrics): make `embed()` defaults to `repository` when `q.repo` is specified

---

source/app/web/statics/style.css

Hey! @lowlighter, I have fixed discussion #900 or issue #901 as can be seen in the screenshot. However, there can be seen a whole lot of lines of code changes, I think that is due to code formatter. Though I have just added two lines of code in one file. I have reverted the previous commit and re-submitted it with only relevant code addition.
- File ```md    source\app\web\statics\style.css  ```
- Code
```md
.ui.top {
border-bottom: 1px solid var(--color-border-secondary);
max-width: 1250px; // New addition
margin: 0 auto; // New addition
} 
```

fix(app/web): misplaced tabs menu issue #901

---

source/plugins/music/index.mjs

Seems that apple completly redesigned their embed player using shadow roots and custom elements which broke apple tracklist mode
Because there are a lot of open connection still open, it's not possible to use `networkIdle0` or `networkIdle2`, so I ended up using an arbitrary wait of 10 seconds... but I'm not really satisfied with this because it seems quite wonky. Should solve the issue while searching for a better solution I guess

fix(plugins/music): apple tracklist (external redesign)

---

package-lock.json
package.json

* **🈷️ Most used languages**
* Verified commits with attached user's gpg keys is now displayed for `indepth` mode #911
* **⏰ WakaTime plugin**
* Add `plugin_wakatime_languages_other` to include other languages stats (#928 @renbaoshuo)
* **👨‍💻 Lines of code changed**
* Changed lines will now be counted towards both added/removed lines #936
* **💡 Coding habits**
* Add `plugin_habits_charts_type` to switch to `chartist` graphs #938
* <img src="https://user-images.githubusercontent.com/22963968/159414228-a774fa36-d2c3-4d0a-903f-7f1669ef1e02.png" width="320">
* **💕 GitHub Sponsors**
* Add `plugin_sponsors_past` to display past sponsorships #958
* <img src="https://user-images.githubusercontent.com/22963968/159411471-b5a1e088-b069-4fb7-9947-da09d7afff8e.png" width="320">
* **🧑‍🤝‍🧑 People …

chore: prepare release v3.22

---

source/plugins/languages/analyzers.mjs
source/plugins/languages/index.mjs
source/plugins/languages/metadata.yml
source/templates/classic/partials/languages.ejs

Relates #857
- Missed lines/bytes/commits are now counted when in `indepth` mode
- Unknown lines/bytes languages are included in this stat
- Fix un-awaited fs io (possibly related to #873 ?)
- Ignore resources busy removal error on cleaning
- Add `--no-merge` when iterating over commit history
- Add `plugin_languages_other` option to group missed/unknown/over-limit languages into a single "Other" category at the end
- On empty results, hide empty bar and display an informational message instead

feat(plugins/languages): various improvements

---

source/plugins/sponsors/index.mjs
source/plugins/sponsors/queries/active.graphql
source/plugins/sponsors/queries/all.graphql
source/plugins/sponsors/queries/description.graphql
source/templates/classic/partials/sponsors.ejs
tests/mocks/api/github/graphql/sponsors.active.mjs
tests/mocks/api/github/graphql/sponsors.all.mjs
tests/mocks/api/github/graphql/sponsors.description.mjs

Instead of only fetching 100 last sponsors and up to 100 last past sponsors, this plugin can now load all of them.
Additionally, sponsoring organizations can be displayed too now

feat(plugins/sponsors): fetch more than 100 sponsors/past sponsors and display organizations

---

source/templates/classic/style.css

Closes #993
Slightly scale up badges to make them more readable, without deforming too much current style

fix(plugins/notable): improve readability of indepth badges

---

source/app/action/index.mjs
source/plugins/core/metadata.yml

Add new option to notice about new official releases of metrics

feat(app/action): add `notice_releases` option

---

source/plugins/sponsors/index.mjs
source/plugins/sponsors/metadata.yml
source/templates/classic/partials/sponsors.ejs
source/templates/classic/style.css

Closes #1000
*Note: `goal` no longer includes `list` by default*

feat(plugins/sponsors): add `list` support to `plugin_sponsors_sections`

---

package-lock.json
package.json

* **🈷️ Most used languages**
* Add `plugin_languages_other` option to group missed, unknown or over-limit languages into a single "Other" category displayed last (#985)
* Missed lines, bytes and commits are now counted in `indepth` mode *(unknown languages are included in this statistic)* (#985)
* <img src="https://user-images.githubusercontent.com/22963968/162860307-cd939415-0997-4b0d-8163-97d0281566c2.png" width="400">
* **💕 GitHub Sponsors**
* Add support for fetching all sponsorships and past sponsorships events rather than the first 100 (#1003)
* Sponsorships from organization are now displayed (#1003)
* Add `list` section to `plugin_sponsors_sections` (#1011)
* *Note: `goal` section no longer includes `list` section by default, which means that both output display can be toggled …

chore: prepare release v3.23

---

source/plugins/calendar/index.mjs
source/plugins/calendar/metadata.yml

Add support for negative numbers so users can display years prior to GitHub registrations

feat(plugins/calendar): add negative number support for `plugin_calendar_limit`

---

source/plugins/notable/index.mjs

As discussed in #1021 , removing the `.sort()` does the job as results are already sorted by stars (thanks to #293).
The code has been tested with a GitHub Action and here is the resulting Gist [before](https://gist.githubusercontent.com/bokub/a299e5bf8043cf7bc08284f339e52468/raw/50bf8b05032300c56bf0e036519dce9c089438a5/github-metrics.svg) and [after](https://gist.githubusercontent.com/bokub/a299e5bf8043cf7bc08284f339e52468/raw/c68bb95327ea82be2916baade7bb297530852d79/github-metrics.svg) the change.
I checked with the GraphQL explorer and the order is good:

fix(plugins/notable): sort contributions by stargazers

---

source/plugins/community/stock/index.mjs
tests/mocks/api/axios/get/yahoo.mjs

As shown in the latest YH Finance API page, the X-RapidAPI-Host has been changed from **apidojo-yahoo-finance-v1.p.rapidapi.com** to **yh-finance.p.rapidapi.com**.  A related discussion can be found in https://github.com/lowlighter/metrics/discussions/931.
Updating obsoleted URL to the new one to avoid 403 error when trying to get the stock chart from this API.

Update X-RapidAPI-Host to yh-finance.p.rapidapi.com

---

action.yml
source/app/action/run.sh

This PR fixes the dependency check outputs. 
On self hosted runners it seems like, that `jq` is not installed all the time. There is already a dependency check which runs before the main action and checks the runner. Unfortunately, the echo is not printing the name to console because when printing a variable, double quotes are needed.
Screenshot of running self hosted without `jq`:
I added the double quotes and escaped the existing ones.

fix: output of missing dependencies

---

source/templates/classic/style.css

Achievement count badge is out of place.
https://bugs.webkit.org/show_bug.cgi?id=241983
Removing the relative position CSS fix the issue on Safari during zooming of SVG as well as in GitHub app markdown view which uses scaled SVG in mobile web view.

Remove relative position which is resetting flexbox container position in Safari.

---

.github/scripts/preview.mjs
source/app/metrics/metadata.mjs
source/app/web/statics/index.html
source/plugins/core/index.mjs
tests/metrics.test.js
vercel.json

fix(ci): vercel

---

package-lock.json
package.json

> ℹ️ This release is mostly focused on **Web instances**.
> If you only use *metrics* through GitHub Actions, you can ignore this version. 
> 🎉 Thanks to all [my sponsors](https://github.com/sponsors/lowlighter), [metrics.lecoq.io](https://metrics.lecoq.io) has been migrated on a more powerful server and should be able to handle more requests!  
* **🌐 Web instances**
* Home page has been redesigned to better guide users through the different features of *metrics*
* `📊 Metrics embed` is now accessible through `/embed/`
* Action and markdown tabs can now be displayed without entering an username
* `✨ Metrics insights` is now accessible through `/insights/`
* Backwards compatibility with previous endpoints has been kept
* `/:login` and `/:login/:repository` will still generate embed metrics …

chore: prepare release v3.26

---

source/plugins/habits/index.mjs
source/plugins/habits/metadata.yml

feat(plugins/habits): add `plugin_habits_languages_threshold`

---

source/plugins/skyline/examples.yml
source/plugins/skyline/index.mjs
source/plugins/skyline/metadata.yml

Tweak a bit the plugin to pass customizable advanced settings
Mostly to support @honzaap / [GithubCity](https://github.com/honzaap/GithubCity) from https://honzaap.github.io/GithubCity

feat(plugins/skyline): add `plugin_skyline_settings`

---

package-lock.json
package.json

> 📣 You can now use [beta-metrics.lecoq.io](https://beta-metrics.lecoq.io) to test upcoming releases of [metrics.lecoq.io](https://metrics.lecoq.io)! 
> 📣 You can now login through GitHub OAuth on [metrics.lecoq.io](https://metrics.lecoq.io) to use your own read-only token (revokable anytime) and access more API intensive features that aren't enabled on the web instance by default!
* **💕 GitHub Sponsors**
* Add `plugin_sponsors_title` to set a custom sponsors section title (#1128, @Lissy93)
* **💡 Coding habits** 
* Add `plugin_habits_languages_threshold` to hide languages below a certain usage threshold (#1138)
* **✨ Stargazers**
* *(This plugin was renamed from "Stargazers over last weeks" to "Stargazers" in the documentation)*
* Add `plugin_stargazers_worldmap` to display a worldmap of …

chore: prepare release v3.27

---

source/app/metrics/metadata.mjs
source/plugins/repositories/index.mjs
source/plugins/repositories/metadata.yml
source/plugins/repositories/queries/random.graphql
source/plugins/repositories/queries/starred.graphql

Closes #1203
Also support `plugin.` prefixed syntax for web instance in case of name collision in options

feat(plugins/repositories): add `plugin_repositories_forks` option

---

.github/actions/spelling/expect.txt
source/app/web/statics/embed/app.placeholder.js
source/plugins/leetcode/README.md
source/plugins/leetcode/examples.yml
source/plugins/leetcode/index.mjs
source/plugins/leetcode/metadata.yml
source/plugins/leetcode/queries/languages.graphql
source/plugins/leetcode/queries/problems.graphql
source/plugins/leetcode/queries/recent.graphql
source/plugins/leetcode/queries/skills.graphql
source/templates/classic/partials/_.json
source/templates/classic/partials/leetcode.ejs
source/templates/classic/style.css
tests/mocks/api/axios/post/leetcode.mjs

feat(plugins/leetcode): add plugin

---

README.md
action.yml
source/plugins/base/README.md
source/plugins/community/chess/README.md
source/plugins/habits/README.md
source/plugins/languages/README.md
source/plugins/languages/metadata.yml
source/plugins/leetcode/README.md
source/plugins/notable/README.md
source/plugins/repositories/README.md
source/plugins/starlists/README.md
source/plugins/starlists/index.mjs
source/plugins/starlists/metadata.yml

Implemented the feature in #1223.
- one fix in plugins/starlists
- the loop below will not be broken if the star list has only one page (which means it doesn't have `.next_page` selector). So I added an extra condition for checking whether break the loop. https://github.com/lowlighter/metrics/blob/cf98a50eb63499d520bea42d8129d1cb8682de0f/source/plugins/starlists/index.mjs#L49-L70
- added the feature
- just same as plugins/languages
- and I also updated `metadata.yml` and `README.md`
- one docs fix in plugins/languages
- the example of `plugins_languages_aliases` is wrong (`javascript:JS typescript:TS`), the separator is a comma instead of whitespace. I fixed that and also added this example to `README.md`.
I have tested the new feature locally using my account and my star lists. It works …

feat(plugins/starlists): add `ignored` and `aliases` for `starlists.languages` and some fix

---

.github/readme/partials/documentation/setup/action.md
source/plugins/core/README.md

Will fix wrong settings keys for `output_action` that probably slipped in during copy pasing (mistakes that just happen to everyone :D).
Addionaly I've spotted another typo and commited it as a little fix on top.

docs(plugins/core): fix output_action description

---

source/app/metrics/index.mjs

fix(app/metrics): irrevelant warnings for `embed` function

---

package-lock.json
source/app/web/statics/embed/app.js
source/app/web/statics/embed/index.html

This PR adds "Copy Markdown Code" button to markdown code tab. Fixes #1164.

feat(app/web): add copy markdown code button

---

source/app/web/statics/insights/index.html

This fixes a bad link introduced in #1098

fix: fix bad GitHub Linguist link

---

source/app/web/statics/insights/index.html

Metrics uses LinguistJS now, should this be changed to link to that instead?
_Originally posted by @Nixinova in https://github.com/lowlighter/metrics/pull/1277#discussion_r1015121961_
Changes the link from https://github.com/github/linguist to https://github.com/Nixinova/LinguistJS

change link from GitHub Linguist to LinguistJS

---

source/plugins/community/splatoon/index.mjs
source/plugins/community/splatoon/metadata.yml
source/plugins/community/splatoon/s3si/index.ts
source/templates/classic/partials/splatoon.ejs

Add player nameplate and overall stats: 
___
<sup>Depends https://github.com/spacemeowx2/s3si.ts/pull/32</sup>

feat(plugins/community/splatoon): player card

---

package-lock.json
package.json

* The action will throw an error when trying to use [GitHub fine-grained personal access tokens](https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/) as `token` as it's not possible to use them to authenticate to GitHub GraphQL API yet
* *If fine-grained PATs can be used for authenticating to GraphQL API in the future, support for them will be considered* 
* **🦑 Splatoon <sup>✨ new!</sup>**
- Configure `plugin_splatoon_token` to display your Splatnet 3 data ! (#1287, #1303)
- Enable `plugin_splatoon_statink` and set `plugin_splatoon_statink_token` for [stat.ink](https://stat.ink/) integration
- Display your `player` nameplate, last `versus` matches and last `salmon-run` shifts using `plugin_splatoon_sections`  !
- Use …

chore: prepare release v3.30

---

source/plugins/core/index.mjs
source/plugins/core/metadata.yml
source/templates/classic/style.css
source/templates/terminal/style.css

Add a new debug flag `--winter` to force the display of winter theme

feat(plugins/core): add support for `--winter` debug flag

---

source/plugins/steam/examples.yml

`""` is necessary for `plugin_steam_user`.
I got this error when it was missing:
Maybe caused by:
```
Steam user id                                                   │ 7.65611984543922E+16
```
https://github.com/CCXXXI/CCXXXI/actions/runs/4542103774/jobs/8005095844#step:2:1053

docs(steam): correct `plugin_steam_user` example

---

source/plugins/achievements/index.mjs

See https://github.com/lowlighter/metrics/issues/1479#issuecomment-1633615855. 
GitHub hide the total data from the homepage of GitHub Search. So I get them by searching `create:>2007` (since GitHub is founded in 2008) as a temporary fix.
This may not obtain the accurate data (especially the total number of repos), but at least it works. Maybe using an api provided by GitHub is the best choice, but I didn't find such an api.
Closes #1479.

fix(achievements): update total data acquisition method

---

source/plugins/achievements/index.mjs

#1479 was not fixed by #1487 for me; I have some private pre-2007 content that continued to generate [#1479’s Unexpected error](https://github.com/lowlighter/metrics/issues/1479#issue-1799689722).
The issue is resolved by [`71f6dbd178`](https://github.com/LucasLarson/metrics/commit/71f6dbd1782a86bf3e1e827a6951b2527afc3498), which changes the search scope from
after 2007 (`>2007`) to
during or after the beginning of the Unix epoch (`>=1970`)

find pre-2007 activity

---

source/plugins/achievements/index.mjs
source/plugins/achievements/queries/total.graphql
tests/mocks/api/github/graphql/achievements.total.mjs

Will first attempts to load total count using github search through GraphQL API for more reliability
If not working, fallback on browser method
Also fixes the current regex to extract results:
```diff
- /(?<type>Repositories|Users|Issues)\n(?<count>.*?)M/g 
// matches [ ", 58", ", 109", ", 119" ]
+ /(?<type>Repositories|Users|Issues)\n.*?(?<count>\d+)M/g
// matches [ "58", "109", "119" ]

fix(plugin/achievements): use graphql first for initial setup and fix regex
